---

- name: Install and enabled MySQL
  block:
    - name: install MySQL-server
      yum:
        name: mysql-server
        state: present
        update_cache: yes

    - name: enabled and start MySQL-server
      service:
        name: mysqld
        enabled: yes
        state: started
