---
- name: Config nginx and static files
  block:
      - name: update nginx config
        template:
          src: templates/nginx.conf.j2
          dest: /etc/nginx/nginx.conf
          owner: root
        notify:
          - reload nginx

      - name: update nginx statis
        copy:
          src: "files/"
          dest: "{{ root_dir }}"
          owner: root
        notify:
          - reload nginx
