---
- name: Docker
  hosts: Ubuntu
  become: true

  tasks:
  - name: update cache
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: Install apt
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-setuptools
        - python3-pip
      state: latest
      update_cache: yes
  - name: Add GPG key
    ansible.builtin.apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
  - name: Add Docker repository
    apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present
  - name: Update apt and install docker-ce
    apt:
        update_cache=yes
        name=docker-ce
        state=latest
  - name: Install Docker Module for Python
    pip:
        name: docker
